/*
Do NOT edit this file!
This file will be deleted with the next Jenkins/Grunt build.
Build Date: Friday, February 23rd, 2018, 3:49:49 AM UTC
Version:fe8e8d778c55cc8c7deb21536aa95ad9d955583c_1519357790
Questions? contact Paolo Vaca 
*/

define("index-desktop-startup",function(){}),require(["index-desktop-startup"]);